export const ACADEMIC_SESSION = "2026-27";
export const SYLLABUS_BOARD = "CBSE (NCERT aligned)";

export type SyllabusSubject = {
  name: string;
  chapters: string[];
};

const syllabusData: Record<number, SyllabusSubject[]> = {
  1: [
    { name: "Mathematics", chapters: ["Shapes and Space", "Numbers from One to Nine", "Addition", "Subtraction", "Numbers from Ten to Twenty", "Time", "Measurement", "Numbers from Twenty-one to Fifty", "Data Handling", "Patterns", "Numbers from Fifty-one to One Hundred", "Money"] },
    { name: "English", chapters: ["Reading Comprehension", "Picture Composition", "Poems & Rhymes", "Simple Sentences", "Naming Words & Action Words", "My Family & School"] },
    { name: "Hindi", chapters: ["वर्णमाला", "मात्राएँ", "सरल शब्द", "दो-तीन शब्दों के वाक्य", "कविता पाठ", "चित्र वर्णन"] },
    { name: "Punjabi", chapters: ["Varanmala", "ਮਾਤਰਾਵਾਂ", "ਸਰਲ ਸ਼ਬਦ", "ਛੋਟੇ ਵਾਕ", "ਕਵਿਤਾ ਪਾਠ", "ਚਿੱਤਰ ਵਰਣਨ"] },
    { name: "EVS", chapters: ["About Me", "My Family", "Food We Eat", "Clothes We Wear", "Plants Around Us", "Animals Around Us", "Our Helpers", "Air & Water", "Good Habits"] },
  ],
  2: [
    { name: "Mathematics", chapters: ["What is Long, What is Round?", "Counting in Groups", "How Much Can You Carry?", "Counting in Tens", "Patterns", "Footprints", "Jugs and Mugs", "Tens and Ones", "My Funday", "Add Our Points", "Lines and Lines", "Give and Take", "The Longest Step", "Birds Come, Birds Go", "How Many Ponytails?"] },
    { name: "English", chapters: ["Reading & Recitation", "Story Writing", "Grammar: Nouns & Verbs", "Picture Reading", "Paragraph Writing", "Opposites & Synonyms"] },
    { name: "Hindi", chapters: ["वर्ण और शब्द", "संज्ञा", "क्रिया", "वाक्य बनाएँ", "अपठित गद्यांश", "पत्र लेखन (सरल)"] },
    { name: "Punjabi", chapters: ["ਵਰਨ ਅਤੇ ਸ਼ਬਦ", "ਸੰਜਾ", "ਕ੍ਰਿਆ", "ਵਾਕ ਬਣਾਓ", "ਅਨਪਠਿਤ ਗਦ", "ਪੱਤਰ ਲੇਖਨ (ਸਰਲ)"] },
    { name: "EVS", chapters: ["Growing Plants", "Animals & Their Shelters", "Water", "Our Food", "Our Houses", "Transport", "Communication", "The Earth", "Work & Play", "Festivals"] },
  ],
  3: [
    { name: "Mathematics", chapters: ["Where to Look From", "Fun with Numbers", "Give and Take", "Long and Short", "Shapes and Designs", "Fun with Give and Take", "Time Goes On", "Who is Heavier?", "How Many Times?", "Play with Patterns", "Jugs and Mugs", "Can We Share?", "Smart Charts!", "Rupees and Paise"] },
    { name: "English", chapters: ["Reading Comprehension", "Story & Paragraph Writing", "Grammar: Nouns, Pronouns, Verbs", "Adjectives & Adverbs", "Letter Writing", "Poetry Appreciation"] },
    { name: "Hindi", chapters: ["संज्ञा और सर्वनाम", "विशेषण", "काल", "वचन और लिंग", "निबंध लेखन", "पत्र लेखन"] },
    { name: "Punjabi", chapters: ["ਸੰਜਾ ਅਤੇ ਸਰਵਨਾਮ", "ਵਿਸ਼ੇਸ਼ਣ", "ਕਾਲ", "ਲਿੰਗ ਅਤੇ ਵਚਨ", "ਨਿਬੰਧ ਲੇਖਨ", "ਪੱਤਰ ਲੇਖਨ"] },
    { name: "EVS", chapters: ["Poonam's Day Out", "The Plant Fairy", "Water O' Water!", "Our First School", "Chhotu's House", "Foods We Eat", "Saying without Speaking", "Flying High", "It's Raining", "What is Cooking", "From Here to There", "Work We Do", "Sharing Our Feelings", "The Story of Food", "Making Pots", "Games We Play", "Here Comes a Letter", "A House Like This!", "Our Friends — Animals", "Drop by Drop", "Families can be Different", "Left-Right", "A Beautiful Cloth", "Web of Life"] },
    { name: "Science", chapters: ["Living & Non-living", "Plants & Animals", "Birds & Nests", "Food & Nutrition", "Human Body", "Measurement", "Light, Sound & Force", "Sun, Moon & Stars", "Water & Weather"] },
    { name: "Social Studies", chapters: ["Our Community", "Maps & Directions", "Means of Transport", "Our Country India", "Festivals & Culture", "Good Citizenship"] },
  ],
  4: [
    { name: "Mathematics", chapters: ["Building with Bricks", "Long and Short", "A Trip to Bhopal", "Tick-Tick-Tick", "The Way The World Looks", "The Junk Seller", "Jugs and Mugs", "Carts and Wheels", "Halves and Quarters", "Play with Patterns", "Tables and Shares", "How Heavy? How Light?", "Fields and Fences", "Smart Charts"] },
    { name: "English", chapters: ["Comprehension Passages", "Essay & Story Writing", "Grammar: Tenses", "Adjectives & Prepositions", "Formal & Informal Letters", "Poetry & Literature"] },
    { name: "Hindi", chapters: ["व्याकरण: संज्ञा, सर्वनाम, विशेषण", "काल और वाच्य", "अपठित गद्यांश", "निबंध लेखन", "पत्र लेखन", "कविता पाठ"] },
    { name: "Punjabi", chapters: ["ਵਿਆਕਰਣ: ਸੰਜਾ, ਸਰਵਨਾਮ", "ਕਾਲ ਅਤੇ ਵਾਚ", "ਅਨਪਠਿਤ ਗਦ", "ਨਿਬੰਧ ਲੇਖਨ", "ਪੱਤਰ ਲੇਖਨ", "ਕਵਿਤਾ ਪਾਠ"] },
    { name: "EVS", chapters: ["Going to School", "Ear to Ear", "A Day with Nandu", "The Story of Amrita", "Anita and the Honeybees", "Omana's Journey", "Reaching Grandmother's House", "Changing Families", "Hu-tu-tu, Hu-tu-tu", "The Valley of Flowers", "A River's Tale", "Basva's Farm", "From Market to Home", "A Busy Month", "Nandita in Mumbai", "Too Much Water, Too Little Water", "Abdul in the Garden", "Eating Together", "Food and Fun", "The World in My Home", "Home and Abroad", "Defence Officer: Wahida", "Chuskit Goes to School"] },
    { name: "Science", chapters: ["Plant Life", "Animal Life", "Human Body", "Food & Digestion", "Matter & Materials", "Force, Work & Energy", "Earth & Environment", "Air & Water"] },
    { name: "Social Studies", chapters: ["Maps & Globes", "Indian States & Capitals", "Physical Features of India", "Our Constitution", "Means of Livelihood", "Transport & Communication"] },
  ],
  5: [
    { name: "Mathematics", chapters: ["The Fish Tale", "Shapes and Angles", "How Many Squares?", "Parts and Wholes", "Does it Look the Same?", "Be My Multiple, I'll Be Your Factor", "Can You See the Pattern?", "Mapping Your Way", "Boxes and Sketches", "Tenths and Hundredths", "Area and its Boundary", "Smart Charts", "Ways to Multiply and Divide", "How Big? How Heavy?"] },
    { name: "English", chapters: ["Reading & Literature", "Essay Writing", "Grammar: Tenses & Modals", "Active & Passive Voice", "Reported Speech", "Letter & Email Writing"] },
    { name: "Hindi", chapters: ["रचना: निबंध, पत्र, अनुच्छेद", "व्याकरण: संधि, समास", "अपठित गद्यांश", "काल और वाच्य", "मुहावरे और लोकोक्तियाँ"] },
    { name: "Punjabi", chapters: ["ਰਚਨਾ: ਨਿਬੰਧ, ਪੱਤਰ, ਅਨੁਛੇਦ", "ਵਿਆਕਰਣ: ਸੰਧੀ, ਸਮਾਸ", "ਅਨਪਠਿਤ ਗਦ", "ਕਾਲ ਅਤੇ ਵਾਚ", "ਮੁਹਾਵਰੇ ਅਤੇ ਅਖਾਣ"] },
    { name: "EVS", chapters: ["Super Senses", "A Snake Charmer's Story", "From Tasting to Digesting", "Mangoes Round the Year", "Seeds and Seeds", "Every Drop Counts", "Experiments with Water", "A Treat for Mosquitoes", "Up You Go!", "Walls Tell Stories", "Sunita in Space", "What if it Finishes...?", "A Shelter so High!", "When the Earth Shook!", "Blow Hot, Blow Cold", "Who will do this Work?", "Across the Wall", "No Place for Us?", "A Seed tells a Farmer's Story", "Whose Forests?", "Like Father, Like Daughter", "On the Move Again"] },
    { name: "Science", chapters: ["Living Things", "Human Body & Health", "Food & Nutrition", "Rocks & Minerals", "Simple Machines", "Light & Shadows", "Air & Water", "Our Environment"] },
    { name: "Social Studies", chapters: ["Globe & Maps", "Major Landforms", "India: Climate & Vegetation", "Democracy & Government", "Local Administration", "Natural Resources"] },
  ],
  6: [
    { name: "Mathematics", chapters: ["Knowing Our Numbers", "Whole Numbers", "Playing with Numbers", "Basic Geometrical Ideas", "Understanding Elementary Shapes", "Integers", "Fractions", "Decimals", "Data Handling", "Mensuration", "Algebra", "Ratio and Proportion", "Symmetry", "Practical Geometry"] },
    { name: "English", chapters: ["Honeysuckle Reader", "A Pact with the Sun", "Grammar: Tenses, Modals", "Active & Passive Voice", "Reported Speech", "Formal Letter Writing", "Essay & Paragraph"] },
    { name: "Hindi", chapters: ["विलोम, पर्यायवाची", "संधि और समास", "अलंकार (उपमा, रूपक)", "निबंध और पत्र लेखन", "अपठित गद्यांश", "काल और वाच्य"] },
    { name: "Punjabi", chapters: ["ਵਿਲੋਮ, ਪਰਿਆਇਵਾਚੀ", "ਸੰਧੀ ਅਤੇ ਸਮਾਸ", "ਅਲੰਕਾਰ (ਉਪਮਾ, ਰੂਪਕ)", "ਨਿਬੰਧ ਅਤੇ ਪੱਤਰ ਲੇਖਨ", "ਅਨਪਠਿਤ ਗਦ", "ਕਾਲ ਅਤੇ ਵਾਚ"] },
    { name: "Science", chapters: ["Food: Where Does it Come From?", "Components of Food", "Fibre to Fabric", "Sorting Materials", "Separation of Substances", "Changes Around Us", "Getting to Know Plants", "Body Movements", "Living Organisms", "Motion & Measurement", "Light, Shadows & Reflections", "Electricity & Circuits", "Fun with Magnets", "Water", "Air Around Us"] },
    { name: "Social Science", chapters: ["Introduction: What, Where, How and When?", "From Hunting-Gathering to Growing Food", "In the Earliest Cities", "What Books and Burials Tell Us", "Kingdoms, Kings and Early Republic", "New Questions and Ideas", "Ashoka the Emperor", "Villages, Towns and Trade", "New Empires and Kingdoms", "Buildings, Paintings and Books", "The Earth in the Solar System", "Globe: Latitudes and Longitudes", "Motions of the Earth", "Maps", "Major Domains of the Earth", "Major Landforms", "Our Country India", "India: Climate, Vegetation and Wildlife", "Understanding Diversity", "Diversity and Discrimination", "What is Government?", "Key Elements of Democracy", "Panchayati Raj", "Rural Administration", "Urban Administration", "Rural Livelihoods", "Urban Livelihoods"] },
  ],
  7: [
    { name: "Mathematics", chapters: ["Integers", "Fractions and Decimals", "Data Handling", "Simple Equations", "Lines and Angles", "The Triangle and its Properties", "Comparing Quantities", "Rational Numbers", "Perimeter and Area", "Algebraic Expressions", "Exponents and Powers", "Symmetry", "Visualising Solid Shapes"] },
    { name: "English", chapters: ["Honeycomb Reader", "An Alien Hand", "Grammar: Clauses & Determiners", "Formal & Informal Letters", "Notice & Message Writing", "Essay & Debate"] },
    { name: "Hindi", chapters: ["विशेषण और क्रिया विशेषण", "वाच्य परिवर्तन", "अलंकार", "पत्र और निबंध लेखन", "अपठित गद्यांश", "संधि और समास"] },
    { name: "Punjabi", chapters: ["ਵਿਸ਼ੇਸ਼ਣ ਅਤੇ ਕ੍ਰਿਆ ਵਿਸ਼ੇਸ਼ਣ", "ਵਾਚ ਪਰਿਵਰਤਨ", "ਅਲੰਕਾਰ", "ਪੱਤਰ ਅਤੇ ਨਿਬੰਧ ਲੇਖਨ", "ਅਨਪਠਿਤ ਗਦ", "ਸੰਧੀ ਅਤੇ ਸਮਾਸ"] },
    { name: "Science", chapters: ["Nutrition in Plants", "Nutrition in Animals", "Fibre to Fabric", "Heat", "Acids, Bases and Salts", "Physical and Chemical Changes", "Weather, Climate and Adaptations", "Winds, Storms and Cyclones", "Soil", "Respiration in Organisms", "Transportation in Animals and Plants", "Reproduction in Plants", "Motion and Time", "Electric Current and its Effects", "Light", "Water: A Precious Resource", "Forests: Our Lifeline", "Wastewater Story"] },
    { name: "Social Science", chapters: ["Tracing Changes Through a Thousand Years", "New Kings and Kingdoms", "The Delhi Sultans", "The Mughal Empire", "Rulers and Buildings", "Towns, Traders and Craftspersons", "Tribes, Nomads and Settled Communities", "Devotional Paths to the Divine", "The Making of Regional Cultures", "Eighteenth-Century Political Formations", "Environment", "Inside Our Earth", "Our Changing Earth", "Air", "Water", "Natural Vegetation and Wildlife", "Human Environment", "Life in the Deserts", "On Equality", "Role of the Government in Health", "How the State Government Works", "Growing up as Boys and Girls", "Women Change the World", "Understanding Media", "Markets Around Us", "A Shirt in the Market"] },
  ],
  8: [
    { name: "Mathematics", chapters: ["Rational Numbers", "Linear Equations in One Variable", "Understanding Quadrilaterals", "Practical Geometry", "Data Handling", "Squares and Square Roots", "Cubes and Cube Roots", "Comparing Quantities", "Algebraic Expressions and Identities", "Visualising Solid Shapes", "Mensuration", "Exponents and Powers", "Direct and Inverse Proportions", "Factorisation", "Introduction to Graphs", "Playing with Numbers"] },
    { name: "English", chapters: ["Honeydew Reader", "It So Happened", "Grammar: Active/Passive, Reported Speech", "Formal Letters & Articles", "Essay & Story Writing", "Literature Analysis"] },
    { name: "Hindi", chapters: ["रचना: निबंध, पत्र, विज्ञापन", "व्याकरण: वाच्य, काल", "अलंकार और मुहावरे", "अपठित गद्यांश", "संधि, समास, उपसर्ग-प्रत्यय"] },
    { name: "Punjabi", chapters: ["ਰਚਨਾ: ਨਿਬੰਧ, ਪੱਤਰ, ਵਿਗਿਆਪਨ", "ਵਿਆਕਰਣ: ਵਾਚ, ਕਾਲ", "ਅਲੰਕਾਰ ਅਤੇ ਮੁਹਾਵਰੇ", "ਅਨਪਠਿਤ ਗਦ", "ਸੰਧੀ, ਸਮਾਸ, ਉਪਸਰਗ-ਪ੍ਰਤਯ"] },
    { name: "Science", chapters: ["Crop Production and Management", "Microorganisms: Friend and Foe", "Synthetic Fibres and Plastics", "Materials: Metals and Non-Metals", "Coal and Petroleum", "Combustion and Flame", "Conservation of Plants and Animals", "Cell Structure and Functions", "Reproduction in Animals", "Reaching the Age of Adolescence", "Force and Pressure", "Friction", "Sound", "Chemical Effects of Electric Current", "Some Natural Phenomena", "Light", "Stars and the Solar System", "Pollution of Air and Water"] },
    { name: "Social Science", chapters: ["How, When and Where", "From Trade to Territory", "Ruling the Countryside", "Tribals, Dikus and Vision of a Golden Age", "When People Rebel", "Civilising the Native, Educating the Nation", "Women, Caste and Reform", "The Making of the National Movement", "India After Independence", "Resources", "Land, Soil, Water, Natural Vegetation and Wildlife", "Mineral and Power Resources", "Agriculture", "Industries", "Human Resources", "The Indian Constitution", "Understanding Secularism", "Why Do We Need a Parliament?", "Understanding Laws", "Judiciary", "Understanding Our Criminal Justice System", "Understanding Marginalisation", "Confronting Marginalisation", "Public Facilities", "Law and Social Justice"] },
  ],
  9: [
    { name: "Mathematics", chapters: ["Number Systems", "Polynomials", "Coordinate Geometry", "Linear Equations in Two Variables", "Introduction to Euclid's Geometry", "Lines and Angles", "Triangles", "Quadrilaterals", "Areas of Parallelograms and Triangles", "Circles", "Constructions", "Heron's Formula", "Surface Areas and Volumes", "Statistics", "Probability"] },
    { name: "English", chapters: ["Beehive Reader", "Moments Supplementary", "Grammar: Modals, Active/Passive", "Reported Speech & Clauses", "Descriptive & Analytical Writing", "Literature: Prose & Poetry"] },
    { name: "Hindi", chapters: ["गद्य और पद्य साहित्य", "रचना: निबंध, पत्र, अनुच्छेद", "व्याकरण: वाच्य, काल, अशुद्धि शोधन", "अपठित गद्यांश", "अलंकार और समास"] },
    { name: "Punjabi", chapters: ["ਗਦ ਅਤੇ ਪਦ ਸਾਹਿਤ", "ਰਚਨਾ: ਨਿਬੰਧ, ਪੱਤਰ, ਅਨੁਛੇਦ", "ਵਿਆਕਰਣ: ਵਾਚ, ਕਾਲ, ਅਸ਼ੁੱਧੀ ਸੋਧ", "ਅਨਪਠਿਤ ਗਦ", "ਅਲੰਕਾਰ ਅਤੇ ਸਮਾਸ"] },
    { name: "Science", chapters: ["Matter in Our Surroundings", "Is Matter Around Us Pure?", "Atoms and Molecules", "Structure of the Atom", "The Fundamental Unit of Life", "Tissues", "Diversity in Living Organisms", "Motion", "Force and Laws of Motion", "Gravitation", "Work and Energy", "Sound", "Why Do We Fall Ill?", "Natural Resources", "Improvement in Food Resources"] },
    { name: "Social Science", chapters: ["The French Revolution", "Socialism in Europe and Russian Revolution", "Nazism and the Rise of Hitler", "Forest Society and Colonialism", "Pastoralists in the Modern World", "Peasants and Farmers", "History and Sport: The Story of Cricket", "Clothing: A Social History", "India: Size and Location", "Physical Features of India", "Drainage", "Climate", "Natural Vegetation and Wildlife", "Population", "What is Democracy? Why Democracy?", "Constitutional Design", "Electoral Politics", "Working of Institutions", "Democratic Rights", "The Story of Village Palampur", "People as Resource", "Poverty as a Challenge", "Food Security in India"] },
  ],
  10: [
    { name: "Mathematics", chapters: ["Real Numbers", "Polynomials", "Pair of Linear Equations in Two Variables", "Quadratic Equations", "Arithmetic Progressions", "Triangles", "Coordinate Geometry", "Introduction to Trigonometry", "Applications of Trigonometry", "Circles", "Constructions", "Areas Related to Circles", "Surface Areas and Volumes", "Statistics", "Probability"] },
    { name: "English", chapters: ["First Flight Reader", "Footprints Without Feet", "Grammar: Tenses, Modals, Clauses", "Letter & Article Writing", "Analytical Paragraph", "Literature: Prose, Poetry & Drama"] },
    { name: "Hindi", chapters: ["क्षितिज भाग 2", "कृतिका भाग 2", "रचना: निबंध, पत्र, विज्ञापन", "व्याकरण: वाच्य, समास, अलंकार", "अपठित गद्यांश"] },
    { name: "Punjabi", chapters: ["ਸਾਹਿਤ ਪਾਠ", "ਰਚਨਾ: ਨਿਬੰਧ, ਪੱਤਰ, ਵਿਗਿਆਪਨ", "ਵਿਆਕਰਣ: ਵਾਚ, ਸਮਾਸ, ਅਲੰਕਾਰ", "ਅਨਪਠਿਤ ਗਦ", "ਬੋਰਡ ਪ੍ਰੀਖਿਆ ਅਭਿਆਸ"] },
    { name: "Science", chapters: ["Chemical Reactions and Equations", "Acids, Bases and Salts", "Metals and Non-metals", "Carbon and its Compounds", "Life Processes", "Control and Coordination", "How do Organisms Reproduce?", "Heredity and Evolution", "Light: Reflection and Refraction", "Human Eye and Colourful World", "Electricity", "Magnetic Effects of Electric Current", "Our Environment", "Sources of Energy", "Sustainable Management of Natural Resources"] },
    { name: "Social Science", chapters: ["The Rise of Nationalism in Europe", "Nationalism in India", "The Making of a Global World", "The Age of Industrialisation", "Print Culture and the Modern World", "Resources and Development", "Forest and Wildlife Resources", "Water Resources", "Agriculture", "Minerals and Energy Resources", "Manufacturing Industries", "Lifelines of National Economy", "Power Sharing", "Federalism", "Gender, Religion and Caste", "Political Parties", "Outcomes of Democracy", "Money and Credit", "Globalisation and the Indian Economy", "Consumer Rights"] },
  ],
  11: [
    { name: "Mathematics", chapters: ["Sets", "Relations and Functions", "Trigonometric Functions", "Complex Numbers", "Linear Inequalities", "Permutations and Combinations", "Binomial Theorem", "Sequences and Series", "Straight Lines", "Conic Sections", "Introduction to Three Dimensional Geometry", "Limits and Derivatives", "Statistics", "Probability"] },
    { name: "Physics", chapters: ["Physical World", "Units and Measurements", "Motion in a Straight Line", "Motion in a Plane", "Laws of Motion", "Work, Energy and Power", "System of Particles", "Rotational Motion", "Gravitation", "Mechanical Properties of Solids", "Mechanical Properties of Fluids", "Thermal Properties of Matter", "Thermodynamics", "Kinetic Theory", "Oscillations", "Waves"] },
    { name: "Chemistry", chapters: ["Some Basic Concepts of Chemistry", "Structure of Atom", "Classification of Elements", "Chemical Bonding", "States of Matter", "Thermodynamics", "Equilibrium", "Redox Reactions", "Hydrogen", "s-Block Elements", "p-Block Elements", "Organic Chemistry Basics", "Hydrocarbons", "Environmental Chemistry"] },
    { name: "Biology", chapters: ["The Living World", "Biological Classification", "Plant Kingdom", "Animal Kingdom", "Morphology of Flowering Plants", "Anatomy of Flowering Plants", "Structural Organisation in Animals", "Cell: The Unit of Life", "Biomolecules", "Cell Cycle and Cell Division", "Transport in Plants", "Mineral Nutrition", "Photosynthesis", "Respiration in Plants", "Plant Growth and Development", "Digestion and Absorption", "Breathing and Exchange of Gases", "Body Fluids and Circulation", "Excretory Products", "Locomotion and Movement", "Neural Control and Coordination", "Chemical Coordination and Integration"] },
    { name: "English", chapters: ["Hornbill Reader", "Snapshots", "Writing Skills: Notice, Article, Speech", "Reading Comprehension", "Literature Analysis"] },
    { name: "Hindi", chapters: ["आरोह: गद्य खंड", "आरोह: काव्य खंड", "वितान: गद्य खंड", "वितान: काव्य खंड", "अपठित गद्यांश", "निबंध लेखन", "पत्र लेखन", "व्याकरण: वाच्य और काल", "व्याकरण: समास और अलंकार"] },
    { name: "Punjabi", chapters: ["ਗੱਦ ਸਾਹਿਤ", "ਕਾਵ ਸਾਹਿਤ", "ਵਿਆਕਰਣ", "ਅਨਪਠਿਤ ਗਦ", "ਨਿਬੰਧ ਲੇਖਨ", "ਪੱਤਰ ਲੇਖਨ", "ਵਾਚ ਅਤੇ ਕਾਲ", "ਸੰਧੀ ਅਤੇ ਅਲੰਕਾਰ"] },
    { name: "Accountancy", chapters: ["Introduction to Accounting", "Theory Base of Accounting", "Recording of Transactions - I", "Recording of Transactions - II", "Bank Reconciliation Statement", "Trial Balance and Rectification of Errors", "Depreciation, Provisions and Reserves", "Bills of Exchange", "Financial Statements - I", "Financial Statements - II", "Accounts from Incomplete Records", "Applications of Computers in Accounting"] },
    { name: "Business Studies", chapters: ["Nature and Purpose of Business", "Forms of Business Organisation", "Public, Private and Global Enterprises", "Business Services", "Emerging Modes of Business", "Social Responsibilities of Business", "Formation of a Company", "Sources of Business Finance", "Small Business", "Internal Trade", "International Business"] },
    { name: "Economics", chapters: ["Introduction", "Collection of Data", "Organisation of Data", "Presentation of Data", "Measures of Central Tendency", "Measures of Dispersion", "Correlation", "Index Numbers", "Use of Statistical Tools"] },
    { name: "Computer Science", chapters: ["Computer System", "Encoding Schemes and Number System", "Emerging Trends", "Introduction to Problem Solving", "Getting Started with Python", "Flow of Control", "Functions", "Strings", "Lists", "Tuples", "Dictionary", "Societal Impact"] },
    { name: "Informatics Practices", chapters: ["Computer System", "Introduction to Python", "Working with Lists and Dictionaries", "Introduction to NumPy", "Data Handling using Pandas", "Data Visualization", "Internet and Web", "Societal Impacts"] },
    { name: "History", chapters: ["From the Beginning of Time", "Writing and City Life", "An Empire Across Three Continents", "The Central Islamic Lands", "Nomadic Empires", "The Three Orders", "Changing Cultural Traditions", "Confrontation of Cultures", "The Industrial Revolution", "Displacing Indigenous Peoples", "Paths to Modernisation"] },
    { name: "Political Science", chapters: ["Political Theory: An Introduction", "Freedom", "Equality", "Social Justice", "Rights", "Citizenship", "Nationalism", "Secularism", "Peace", "Development", "Constitution: Why and How?", "Rights in the Indian Constitution", "Election and Representation", "Executive", "Legislature", "Judiciary", "Federalism", "Local Governments", "Constitution as a Living Document"] },
    { name: "Geography", chapters: ["Geography as a Discipline", "The Origin and Evolution of the Earth", "Interior of the Earth", "Distribution of Oceans and Continents", "Minerals and Rocks", "Geomorphic Processes", "Landforms and their Evolution", "Composition and Structure of Atmosphere", "Solar Radiation, Heat Balance and Temperature", "Atmospheric Circulation and Weather Systems", "Water in the Atmosphere", "World Climate and Climate Change", "Water (Oceans)", "Movements of Ocean Water", "Life on the Earth", "Biodiversity and Conservation", "India: Location", "Structure and Physiography", "Drainage System", "Climate", "Natural Vegetation", "Natural Hazards and Disasters"] },
    { name: "Psychology", chapters: ["What is Psychology?", "Methods of Enquiry in Psychology", "The Bases of Human Behaviour", "Human Development", "Sensory, Attentional and Perceptual Processes", "Learning", "Human Memory", "Thinking", "Motivation and Emotion"] },
    { name: "Sociology", chapters: ["Sociology and Society", "Terms, Concepts and their Use in Sociology", "Understanding Social Institutions", "Culture and Socialisation", "Doing Sociology: Research Methods", "Social Stratification", "Rural and Urban Societies", "Environment and Society", "Introducing Western Sociologists", "Indian Sociologists"] },
  ],
  12: [
    { name: "Mathematics", chapters: ["Relations and Functions", "Inverse Trigonometric Functions", "Matrices", "Determinants", "Continuity and Differentiability", "Applications of Derivatives", "Integrals", "Applications of Integrals", "Differential Equations", "Vector Algebra", "Three Dimensional Geometry", "Linear Programming", "Probability"] },
    { name: "Physics", chapters: ["Electric Charges and Fields", "Electrostatic Potential and Capacitance", "Current Electricity", "Moving Charges and Magnetism", "Magnetism and Matter", "Electromagnetic Induction", "Alternating Current", "Electromagnetic Waves", "Ray Optics and Optical Instruments", "Wave Optics", "Dual Nature of Radiation and Matter", "Atoms", "Nuclei", "Semiconductor Electronics", "Communication Systems"] },
    { name: "Chemistry", chapters: ["The Solid State", "Solutions", "Electrochemistry", "Chemical Kinetics", "Surface Chemistry", "General Principles of Isolation of Elements", "p-Block Elements", "d and f Block Elements", "Coordination Compounds", "Haloalkanes and Haloarenes", "Alcohols, Phenols and Ethers", "Aldehydes, Ketones and Carboxylic Acids", "Amines", "Biomolecules", "Polymers", "Chemistry in Everyday Life"] },
    { name: "Biology", chapters: ["Reproduction in Organisms", "Sexual Reproduction in Flowering Plants", "Human Reproduction", "Reproductive Health", "Principles of Inheritance and Variation", "Molecular Basis of Inheritance", "Evolution", "Human Health and Disease", "Strategies for Enhancement in Food Production", "Microbes in Human Welfare", "Biotechnology: Principles and Processes", "Biotechnology and its Applications", "Organisms and Populations", "Ecosystem", "Biodiversity and Conservation", "Environmental Issues"] },
    { name: "English", chapters: ["Flamingo Reader", "Vistas", "Writing: Invitations, Letters, Reports", "Reading & Literature", "Board Exam Essay Practice"] },
    { name: "Hindi", chapters: ["आरोह भाग 2: गद्य", "आरोह भाग 2: काव्य", "वितान भाग 2: गद्य", "वितान भाग 2: काव्य", "अपठित गद्यांश", "निबंध लेखन", "पत्र लेखन", "व्याकरण: वाच्य और अशुद्धि शोधन", "रचना अभ्यास"] },
    { name: "Punjabi", chapters: ["ਗੱਦ ਸਾਹਿਤ ਭਾਗ 2", "ਕਾਵ ਸਾਹਿਤ ਭਾਗ 2", "ਵਿਆਕਰਣ", "ਅਨਪਠਿਤ ਗਦ", "ਨਿਬੰਧ ਲੇਖਨ", "ਪੱਤਰ ਲੇਖਨ", "ਵਾਚ ਅਤੇ ਅਸ਼ੁੱਧੀ ਸੋਧ", "ਬੋਰਡ ਲੇਖਨ ਅਭਿਆਸ"] },
    { name: "Accountancy", chapters: ["Accounting for Not-for-Profit Organisation", "Accounting for Partnership: Basic Concepts", "Reconstitution of a Partnership Firm - Admission", "Reconstitution of a Partnership Firm - Retirement", "Reconstitution of a Partnership Firm - Death", "Dissolution of Partnership Firm", "Accounting for Share Capital", "Issue and Redemption of Debentures", "Financial Statements of a Company", "Analysis of Financial Statements", "Accounting Ratios", "Cash Flow Statement"] },
    { name: "Business Studies", chapters: ["Nature and Significance of Management", "Principles of Management", "Business Environment", "Planning", "Organising", "Staffing", "Directing", "Controlling", "Financial Management", "Financial Markets", "Marketing", "Consumer Protection"] },
    { name: "Economics", chapters: ["Introduction to Microeconomics", "Theory of Consumer Behaviour", "Production and Costs", "The Theory of the Firm under Perfect Competition", "Market Equilibrium", "Non-competitive Markets", "Introduction to Macroeconomics", "National Income Accounting", "Money and Banking", "Determination of Income and Employment", "Government Budget and the Economy", "Open Economy Macroeconomics"] },
    { name: "Computer Science", chapters: ["Python Revision Tour", "Exception Handling", "File Handling", "Stack", "Queue", "Sorting", "Searching", "Understanding Data", "Database Concepts", "Structured Query Language", "Computer Networks", "Data Communication", "Security Aspects", "Project Work"] },
    { name: "Informatics Practices", chapters: ["Data Handling using Pandas - II", "Data Visualization", "Internet and Web", "Societal Impacts", "Project Work"] },
    { name: "History", chapters: ["Bricks, Beads and Bones", "Kings, Farmers and Towns", "Kinship, Caste and Class", "Thinkers, Beliefs and Buildings", "Through the Eyes of Travellers", "Bhakti-Sufi Traditions", "An Imperial Capital: Vijayanagara", "Peasants, Zamindars and the State", "Colonialism and the Countryside", "Rebels and the Raj", "Mahatma Gandhi and the National Movement", "Framing the Constitution"] },
    { name: "Political Science", chapters: ["The Cold War Era", "The End of Bipolarity", "US Hegemony in World Politics", "Alternative Centres of Power", "Contemporary South Asia", "International Organisations", "Security in the Contemporary World", "Environment and Natural Resources", "Globalisation", "Challenges of Nation Building", "Era of One-Party Dominance", "Politics of Planned Development", "India's External Relations", "Challenges to and Restoration of the Congress System", "The Crisis of Democratic Order", "Rise of Popular Movements", "Regional Aspirations", "Recent Developments in Indian Politics"] },
    { name: "Geography", chapters: ["Human Geography: Nature and Scope", "The World Population", "Population Composition", "Human Development", "Primary Activities", "Secondary Activities", "Tertiary and Quaternary Activities", "Transport and Communication", "International Trade", "Human Settlements", "India: Population", "Migration", "Human Settlements", "Land Resources and Agriculture", "Water Resources", "Mineral and Energy Resources", "Manufacturing Industries", "Planning and Sustainable Development", "Transport and Communication", "International Trade", "Geographical Perspective on Selected Issues"] },
    { name: "Psychology", chapters: ["Variations in Psychological Attributes", "Self and Personality", "Meeting Life Challenges", "Psychological Disorders", "Therapeutic Approaches", "Attitude and Social Cognition", "Social Influence and Group Processes", "Psychology and Life", "Developing Psychological Skills"] },
    { name: "Sociology", chapters: ["Structural Change", "Cultural Change", "The Story of Indian Democracy", "Change and Development in Rural Society", "Change and Development in Industrial Society", "Globalisation and Social Change", "Mass Media and Communications", "Social Movements"] },
  ],
};

export function getSyllabusForClass(classNumber: number): SyllabusSubject[] {
  return syllabusData[classNumber] ?? [];
}

export function getTotalChapters(classNumber: number): number {
  return getSyllabusForClass(classNumber).reduce((sum, s) => sum + s.chapters.length, 0);
}

export function getSubjectNamesForClass(classNumber: number): string[] {
  return getSyllabusForClass(classNumber).map((s) => s.name);
}
