<?php
declare(strict_types=1);

function syllabus_data(): array
{
    static $data = null;
    if ($data !== null) {
        return $data;
    }

    $session = '2026-27';

    $data = [
        1 => [
            'class' => 1,
            'session' => $session,
            'title' => 'Class 1 CBSE Syllabus 2026-27',
            'description' => 'Foundational syllabus for Class 1 covering early literacy, numeracy, and environmental awareness aligned with NCERT Marigold, Math-Magic, and Rimjhim.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Shapes and Space — identifying circles, squares, triangles, and positional words',
                        'Unit 2: Numbers from One to Nine — counting, comparing, and ordering',
                        'Unit 3: Addition — combining two groups and simple word problems',
                        'Unit 4: Subtraction — taking away and finding the difference',
                        'Unit 5: Numbers from Ten to Twenty — place value and number patterns',
                        'Unit 6: Time — reading a clock to the hour and sequencing daily events',
                        'Unit 7: Measurement — longer/shorter, heavier/lighter, more/less',
                        'Unit 8: Data Handling — pictographs and simple sorting',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Alphabet and Phonics — letter recognition and initial sounds',
                        'Unit 2: Two-Letter and Three-Letter Words — blending and simple reading',
                        'Unit 3: My Family and Friends — themed vocabulary and picture talk',
                        'Unit 4: Action Words — verbs for daily activities',
                        'Unit 5: Rhymes and Stories — listening, reciting, and retelling',
                        'Unit 6: Sentence Formation — subject–verb patterns with capital letters and full stops',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: स्वर और व्यंजन — Hindi varnmala recognition',
                        'Unit 2: मात्राएँ — basic matras and two-letter words',
                        'Unit 3: परिवार और स्कूल — themed vocabulary',
                        'Unit 4: कविता और कहानी — rhymes and short stories',
                        'Unit 5: सरल वाक्य लेखन — picture-based sentence writing',
                    ],
                ],
                [
                    'name' => 'EVS',
                    'units' => [
                        'Unit 1: About Me — name, age, family members, and body parts',
                        'Unit 2: My Needs — food, clothing, shelter, and water',
                        'Unit 3: My Family — roles, love, and care at home',
                        'Unit 4: Keeping Clean and Healthy — hygiene and good habits',
                        'Unit 5: Plants and Animals Around Us — living and non-living things',
                        'Unit 6: Our Surroundings — home, school, and neighbourhood',
                    ],
                ],
            ],
        ],
        2 => [
            'class' => 2,
            'session' => $session,
            'title' => 'Class 2 CBSE Syllabus 2026-27',
            'description' => 'Class 2 syllabus building on reading fluency, two-digit arithmetic, and everyday science concepts through NCERT-aligned chapters.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: What Is Long, What Is Round? — shapes and rolling/sliding objects',
                        'Unit 2: Counting in Groups — skip counting by 2s, 5s, and 10s',
                        'Unit 3: How Much Can You Carry? — comparing weights informally',
                        'Unit 4: Counting in Tens — place value with tens and ones',
                        'Unit 5: Patterns — number and shape patterns',
                        'Unit 6: Footprints — tracing shapes and spatial reasoning',
                        'Unit 7: Jugs and Mugs — capacity and volume comparison',
                        'Unit 8: Tens and Ones — addition and subtraction up to 99',
                        'Unit 9: My Funday — calendar and days of the week',
                        'Unit 10: Add Our Points — mental math strategies',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading Fluency — short passages and sight words',
                        'Unit 2: Nouns and Pronouns — naming words and I/you/he/she',
                        'Unit 3: Describing Words — adjectives for size, colour, and shape',
                        'Unit 4: Story Reading — comprehension questions and sequencing',
                        'Unit 5: Writing Sentences — capital letters, full stops, and question marks',
                        'Unit 6: Creative Expression — picture composition and oral description',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: दो और तीन अक्षर के शब्द — reading practice',
                        'Unit 2: संज्ञा और सर्वनाम — basic grammar',
                        'Unit 3: विलोम और पर्यायवाची — antonyms and synonyms (introductory)',
                        'Unit 4: अपठित गद्यांश — unseen passage with simple questions',
                        'Unit 5: चित्र वर्णन — describing pictures in Hindi',
                    ],
                ],
                [
                    'name' => 'EVS',
                    'units' => [
                        'Unit 1: Growing Up — changes as we grow and stages of life',
                        'Unit 2: Good Habits — manners, sharing, and helping others',
                        'Unit 3: Food We Eat — types of food and a balanced diet',
                        'Unit 4: Clothes We Wear — fabrics and seasonal clothing',
                        'Unit 5: Houses and Shelter — types of homes',
                        'Unit 6: Water — sources, uses, and saving water',
                        'Unit 7: Travel — means of transport and safety rules',
                    ],
                ],
            ],
        ],
        3 => [
            'class' => 3,
            'session' => $session,
            'title' => 'Class 3 CBSE Syllabus 2026-27',
            'description' => 'Intermediate primary syllabus introducing multiplication, paragraph writing, and map skills across core subjects.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Where to Look From — views of objects from different angles',
                        'Unit 2: Fun with Numbers — numbers up to 999 and place value',
                        'Unit 3: Give and Take — addition and subtraction with regrouping',
                        'Unit 4: Long and Short — measuring length using cm and m',
                        'Unit 5: Shapes and Designs — 2D shapes and symmetry',
                        'Unit 6: Fun with Give and Take — word problems',
                        'Unit 7: Time Goes On — reading clocks and elapsed time',
                        'Unit 8: Who Is Heavier? — comparing mass using standard units',
                        'Unit 9: How Many Times? — introduction to multiplication',
                        'Unit 10: Play with Patterns — growing patterns and tables',
                        'Unit 11: Jugs and Mugs — litres and millilitres',
                        'Unit 12: Can We Share? — division as equal sharing',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading Comprehension — main idea and supporting details',
                        'Unit 2: Grammar — verbs, tenses (simple present and past)',
                        'Unit 3: Paragraph Writing — topic sentences and 4–5 sentence paragraphs',
                        'Unit 4: Letter Writing — informal letters to friends and family',
                        'Unit 5: Poetry Appreciation — rhyme, rhythm, and meaning',
                        'Unit 6: Vocabulary Building — synonyms, antonyms, and word families',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: संज्ञा, लिंग, वचन — noun gender and number',
                        'Unit 2: क्रिया — verbs and sentence formation',
                        'Unit 3: निबंध लेखन — short essays on familiar topics',
                        'Unit 4: पत्र लेखन — informal Hindi letters',
                        'Unit 5: Kavita Path — poetry recitation and meaning',
                    ],
                ],
                [
                    'name' => 'EVS',
                    'units' => [
                        'Unit 1: Family and Friends — relationships and community helpers',
                        'Unit 2: Food and Nutrition — nutrients and healthy eating',
                        'Unit 3: Water — water cycle and conservation',
                        'Unit 4: Shelter — materials used in building homes',
                        'Unit 5: Travel and Communication — post, telephone, and internet basics',
                        'Unit 6: Work and Play — occupations and leisure activities',
                        'Unit 7: Plants and Animals — habitats and adaptation (introductory)',
                    ],
                ],
            ],
        ],
        4 => [
            'class' => 4,
            'session' => $session,
            'title' => 'Class 4 CBSE Syllabus 2026-27',
            'description' => 'Class 4 syllabus covering fractions, formal grammar, matter and energy, and an introduction to Indian geography and history.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Building with Bricks — area and tiling patterns',
                        'Unit 2: Long and Short — perimeter introduction and measurement',
                        'Unit 3: A Trip to Bhopal — large-number operations and estimation',
                        'Unit 4: Tick-Tick-Tick — time, calendars, and timelines',
                        'Unit 5: The Way the World Looks — maps and directions',
                        'Unit 6: The Junk Seller — money, profit, and loss basics',
                        'Unit 7: Jugs and Mugs — capacity word problems',
                        'Unit 8: Carts and Wheels — circles and circumference idea',
                        'Unit 9: Halves and Quarters — fractions of shapes and numbers',
                        'Unit 10: Play with Patterns — number puzzles and logic',
                        'Unit 11: Tables and Shares — multiplication tables and division',
                        'Unit 12: How Heavy? How Light? — grams and kilograms',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Parts of Speech — nouns, pronouns, verbs, adjectives, adverbs',
                        'Unit 2: Tenses — present, past, and future continuous (introductory)',
                        'Unit 3: Story Writing — beginning, middle, and end structure',
                        'Unit 4: Comprehension — inference and vocabulary in context',
                        'Unit 5: Formal and Informal Writing — notices and messages',
                        'Unit 6: Literature — prose and poetry from NCERT Marigold',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: विशेषण और क्रिया विशेषण — adjectives and adverbs',
                        'Unit 2: वाक्य शुद्धि — correcting common errors',
                        'Unit 3: अपठित गद्यांश — unseen passages with MCQs',
                        'Unit 4: निबंध और पत्र — essays and formal letters',
                        'Unit 5: मुहावरे — common idioms and their usage',
                    ],
                ],
                [
                    'name' => 'EVS',
                    'units' => [
                        'Unit 1: Going to School — safety on the road and at school',
                        'Unit 2: Ear to Ear — sound and how we hear',
                        'Unit 3: A Day with Nandu — animal behaviour and adaptation',
                        'Unit 4: The Story of Amrita — forests and wildlife protection',
                        'Unit 5: Anita and the Honeybees — insects and pollination',
                        'Unit 6: Omana\'s Journey — Kerala and coastal life',
                        'Unit 7: Reaching Grandmother\'s House — transport across India',
                        'Unit 8: Changing Families — family structures and migration',
                        'Unit 9: Hu Tu Tu, Hu Tu Tu — traditional games and recreation',
                        'Unit 10: Changing Times — technology and communication',
                    ],
                ],
            ],
        ],
        5 => [
            'class' => 5,
            'session' => $session,
            'title' => 'Class 5 CBSE Syllabus 2026-27',
            'description' => 'Upper primary syllabus preparing students for middle school with decimals, essay writing, human body systems, and civics fundamentals.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: The Fish Tale — large numbers and Indian number system',
                        'Unit 2: Shapes and Angles — types of angles and polygons',
                        'Unit 3: How Many Squares? — area on grid paper',
                        'Unit 4: Parts and Wholes — fractions and equivalent fractions',
                        'Unit 5: Does It Look the Same? — symmetry and mirror images',
                        'Unit 6: Be My Multiple, I\'ll Be Your Factor — factors, multiples, LCM, HCF',
                        'Unit 7: Can You See the Pattern? — number and shape sequences',
                        'Unit 8: Mapping Your Way — scale and map reading',
                        'Unit 9: Boxes and Sketches — nets of 3D shapes',
                        'Unit 10: Tenths and Hundredths — decimals and money',
                        'Unit 11: Area and Its Boundary — perimeter and area of rectangles',
                        'Unit 12: Smart Charts — bar graphs and data interpretation',
                        'Unit 13: Ways to Multiply and Divide — algorithms and word problems',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Essay Writing — descriptive and narrative essays (150 words)',
                        'Unit 2: Grammar — active/passive voice (introductory), direct/indirect speech',
                        'Unit 3: Reading Skills — summarising and note-making',
                        'Unit 4: Letter Writing — formal letters (application, complaint)',
                        'Unit 5: Literature — NCERT chapters with character analysis',
                        'Unit 6: Vocabulary — prefixes, suffixes, and compound words',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: संधि और समास — introductory word formation',
                        'Unit 2: अलंकार — simile and metaphor in Hindi poetry',
                        'Unit 3: निबंध लेखन — 150–200 word essays',
                        'Unit 4: अपठित गद्यांश और कविता — unseen passages',
                        'Unit 5: व्याकरण — कारक, वाच्य, and sentence transformation',
                    ],
                ],
                [
                    'name' => 'EVS',
                    'units' => [
                        'Unit 1: Super Senses — animal senses and survival',
                        'Unit 2: A Snake Charmer\'s Story — biodiversity and livelihoods',
                        'Unit 3: From Tasting to Digesting — digestive system and nutrition',
                        'Unit 4: Mangoes Round the Year — food preservation and spoilage',
                        'Unit 5: Seeds and Seeds — plant reproduction and germination',
                        'Unit 6: Every Drop Counts — water scarcity and rainwater harvesting',
                        'Unit 7: Experiments with Water — solubility and density',
                        'Unit 8: A Treat for Mosquitoes — diseases and prevention',
                        'Unit 9: Up You Go! — mountaineering and adventure sports',
                        'Unit 10: Walls Tell Stories — monuments and heritage',
                        'Unit 11: Sunita in Space — solar system and gravity',
                        'Unit 12: What If It Finishes? — natural resources and conservation',
                        'Unit 13: A Shelter So High! — Ladakh and desert life',
                        'Unit 14: When the Earth Shook! — earthquakes and disaster preparedness',
                        'Unit 15: Blow Hot, Blow Cold — temperature and weather',
                        'Unit 16: Who Will Do This Work? — dignity of labour and sanitation',
                        'Unit 17: Across the Wall — gender equality and opportunity',
                        'Unit 18: No Place for Us? — migration and displacement',
                        'Unit 19: A Seed Tells a Farmer\'s Story — agriculture and crops',
                        'Unit 20: Whose Forests? — forests, tribals, and rights',
                        'Unit 21: Like Father, Like Daughter — inheritance and traits',
                        'Unit 22: On the Move Again — nomadic communities',
                    ],
                ],
            ],
        ],
        6 => [
            'class' => 6,
            'session' => $session,
            'title' => 'Class 6 CBSE Syllabus 2026-27',
            'description' => 'Middle school syllabus introducing separate Science and Social Science textbooks with algebra foundations and formal writing skills.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Knowing Our Numbers — comparing and operating on large numbers',
                        'Unit 2: Whole Numbers — properties and number line',
                        'Unit 3: Playing with Numbers — factors, multiples, and divisibility tests',
                        'Unit 4: Basic Geometrical Ideas — points, lines, angles, and curves',
                        'Unit 5: Understanding Elementary Shapes — types of triangles and quadrilaterals',
                        'Unit 6: Integers — addition and subtraction on the number line',
                        'Unit 7: Fractions — operations and word problems',
                        'Unit 8: Decimals — place value and operations',
                        'Unit 9: Data Handling — bar graphs, mean, and pictographs',
                        'Unit 10: Mensuration — perimeter and area of rectangles',
                        'Unit 11: Algebra — variables, expressions, and simple equations',
                        'Unit 12: Ratio and Proportion — unitary method',
                        'Unit 13: Symmetry — line symmetry and reflection',
                        'Unit 14: Practical Geometry — constructing circles and line segments',
                    ],
                ],
                [
                    'name' => 'Science',
                    'units' => [
                        'Unit 1: Food — sources, components, and balanced diet',
                        'Unit 2: Components of Food — carbohydrates, proteins, fats, vitamins',
                        'Unit 3: Fibre to Fabric — plant and animal fibres',
                        'Unit 4: Sorting Materials into Groups — properties of materials',
                        'Unit 5: Separation of Substances — filtration, evaporation, and churning',
                        'Unit 6: Changes Around Us — reversible and irreversible changes',
                        'Unit 7: Getting to Know Plants — root, stem, leaf, and flower',
                        'Unit 8: Body Movements — joints and locomotion in animals',
                        'Unit 9: The Living Organisms — habitat, adaptation, and characteristics',
                        'Unit 10: Motion and Measurement of Distances — standard units',
                        'Unit 11: Light, Shadows and Reflections — transparent, translucent, opaque',
                        'Unit 12: Electricity and Circuits — cells, bulbs, and switches',
                        'Unit 13: Fun with Magnets — magnetic and non-magnetic materials',
                        'Unit 14: Water — circulation, groundwater, and conservation',
                        'Unit 15: Air Around Us — composition and importance',
                        'Unit 16: Garbage In, Garbage Out — waste management and recycling',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading Comprehension — factual and literary passages',
                        'Unit 2: Grammar — subject–verb agreement, modals, and determiners',
                        'Unit 3: Writing — formal and informal letters, messages, and notices',
                        'Unit 4: Creative Writing — story completion and diary entries',
                        'Unit 5: Literature — Honeycomb prose and A Pact with the Sun supplementary',
                        'Unit 6: Speaking and Listening — debate and group discussion basics',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: वर्ण विचार और संधि — advanced spelling rules',
                        'Unit 2: सर्वनाम, विशेषण, क्रिया — parts of speech in depth',
                        'Unit 3: अपठित गद्यांश — unseen passages with analytical questions',
                        'Unit 4: निबंध, पत्र, और अनुच्छेद — structured writing tasks',
                        'Unit 5: कविता खंड — poetry from Vasant textbook',
                    ],
                ],
                [
                    'name' => 'SST',
                    'units' => [
                        'Unit 1: History — What, Where, How and When? (introduction to sources)',
                        'Unit 2: History — From Hunting-Gathering to Growing Food',
                        'Unit 3: History — In the Earliest Cities (Harappan civilisation)',
                        'Unit 4: History — What Books and Burials Tell Us (Vedic period)',
                        'Unit 5: History — Kingdoms, Kings and an Early Republic',
                        'Unit 6: Geography — The Earth in the Solar System',
                        'Unit 7: Geography — Globe: Latitudes and Longitudes',
                        'Unit 8: Geography — Motions of the Earth — rotation and revolution',
                        'Unit 9: Geography — Maps — types, scale, and symbols',
                        'Unit 10: Civics — Understanding Diversity and discrimination',
                        'Unit 11: Civics — Key Elements of a Democratic Government',
                    ],
                ],
            ],
        ],
        7 => [
            'class' => 7,
            'session' => $session,
            'title' => 'Class 7 CBSE Syllabus 2026-27',
            'description' => 'Class 7 syllabus with linear equations, acids and bases, medieval Indian history, and advanced English comprehension.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Integers — properties and operations',
                        'Unit 2: Fractions and Decimals — multiplication and division',
                        'Unit 3: Data Handling — mean, median, mode, and probability intro',
                        'Unit 4: Simple Equations — solving one-variable equations',
                        'Unit 5: Lines and Angles — complementary, supplementary, and transversal',
                        'Unit 6: The Triangle and Its Properties — angle sum and Pythagoras intro',
                        'Unit 7: Comparing Quantities — percentages, profit, loss, and interest',
                        'Unit 8: Rational Numbers — operations and representation',
                        'Unit 9: Perimeter and Area — circles, parallelograms, and triangles',
                        'Unit 10: Algebraic Expressions — addition, subtraction, and factorisation intro',
                        'Unit 11: Exponents and Powers — laws of exponents',
                        'Unit 12: Symmetry — rotational symmetry',
                        'Unit 13: Visualising Solid Shapes — nets, faces, edges, and vertices',
                    ],
                ],
                [
                    'name' => 'Science',
                    'units' => [
                        'Unit 1: Nutrition in Plants — photosynthesis and modes of nutrition',
                        'Unit 2: Nutrition in Animals — digestion in humans and ruminants',
                        'Unit 3: Fibre to Fabric — wool and silk processing',
                        'Unit 4: Heat — temperature, transfer, and laboratory thermometer',
                        'Unit 5: Acids, Bases and Salts — indicators and neutralisation',
                        'Unit 6: Physical and Chemical Changes — rusting and crystallisation',
                        'Unit 7: Weather, Climate and Adaptations of Animals to Climate',
                        'Unit 8: Winds, Storms and Cyclones — air pressure and safety',
                        'Unit 9: Soil — composition, profile, and conservation',
                        'Unit 10: Respiration in Organisms — aerobic and anaerobic respiration',
                        'Unit 11: Transportation in Animals and Plants — blood and vascular tissues',
                        'Unit 12: Reproduction in Plants — asexual and sexual reproduction',
                        'Unit 13: Motion and Time — speed, distance-time graphs',
                        'Unit 14: Electric Current and Its Effects — heating and magnetic effects',
                        'Unit 15: Light — reflection, refraction, and lenses',
                        'Unit 16: Water: A Precious Resource — groundwater and water management',
                        'Unit 17: Forests: Our Lifeline — food chains and interdependence',
                        'Unit 18: Wastewater Story — sewage treatment and sanitation',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading — discursive and case-based passages',
                        'Unit 2: Grammar — clauses, phrasal verbs, and reported speech',
                        'Unit 3: Writing — articles, speech writing, and paragraph expansion',
                        'Unit 4: Literature — Honeycomb and An Alien Hand supplementary reader',
                        'Unit 5: Formal Writing — applications and email etiquette',
                        'Unit 6: Integrated Grammar — gap filling, editing, and omission',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: समास और उपसर्ग-प्रत्यय — compound word formation',
                        'Unit 2: मुहावरे और लोकोक्तियाँ — idioms in context',
                        'Unit 3: अपठित गद्यांश — analytical and vocabulary-based questions',
                        'Unit 4: निबंध और विज्ञापन लेखन — essays and advertisement writing',
                        'Unit 5: कविता और गद्य — Vasant textbook chapters',
                    ],
                ],
                [
                    'name' => 'SST',
                    'units' => [
                        'Unit 1: History — Tracing Changes Through a Thousand Years',
                        'Unit 2: History — New Kings and Kingdoms (Rajputs, Cholas)',
                        'Unit 3: History — The Delhi Sultans — administration and architecture',
                        'Unit 4: History — The Mughal Empire — Akbar to Aurangzeb',
                        'Unit 5: History — Rulers and Buildings — temples, mosques, and forts',
                        'Unit 6: History — Tribes, Nomads and Settled Communities',
                        'Unit 7: History — Devotional Paths to the Divine — Bhakti and Sufi traditions',
                        'Unit 8: Geography — Environment — natural and human environment',
                        'Unit 9: Geography — Inside Our Earth — rocks, minerals, and layers',
                        'Unit 10: Geography — Our Changing Earth — earthquakes and landforms',
                        'Unit 11: Geography — Air and Water — composition and circulation',
                        'Unit 12: Civics — On Equality and role of the government',
                        'Unit 13: Civics — How the State Government Works',
                        'Unit 14: Civics — Growing Up as Boys and Girls — gender roles',
                    ],
                ],
            ],
        ],
        8 => [
            'class' => 8,
            'session' => $session,
            'title' => 'Class 8 CBSE Syllabus 2026-27',
            'description' => 'Class 8 syllabus covering algebraic identities, force and pressure, modern Indian history, and formal essay writing ahead of secondary school.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Rational Numbers — closure, commutativity, and reciprocals',
                        'Unit 2: Linear Equations in One Variable — applications',
                        'Unit 3: Understanding Quadrilaterals — angles sum and types',
                        'Unit 4: Practical Geometry — constructing quadrilaterals',
                        'Unit 5: Data Handling — pie charts, probability, and grouped data',
                        'Unit 6: Squares and Square Roots — patterns and estimation',
                        'Unit 7: Cubes and Cube Roots — prime factorisation method',
                        'Unit 8: Comparing Quantities — compound interest and discount',
                        'Unit 9: Algebraic Expressions and Identities — (a+b)² and factorisation',
                        'Unit 10: Visualising Solid Shapes — views and mapping space',
                        'Unit 11: Mensuration — surface area and volume of cuboids and cylinders',
                        'Unit 12: Exponents and Powers — negative exponents and standard form',
                        'Unit 13: Direct and Inverse Proportions — word problems',
                        'Unit 14: Factorisation — common factors and identities',
                        'Unit 15: Introduction to Graphs — linear graphs and coordinates',
                        'Unit 16: Playing with Numbers — divisibility and number puzzles',
                    ],
                ],
                [
                    'name' => 'Science',
                    'units' => [
                        'Unit 1: Crop Production and Management — agricultural practices',
                        'Unit 2: Microorganisms: Friend and Foe — bacteria, fungi, and viruses',
                        'Unit 3: Synthetic Fibres and Plastics — polymers and environmental impact',
                        'Unit 4: Materials: Metals and Non-Metals — properties and reactions',
                        'Unit 5: Coal and Petroleum — fossil fuels and conservation',
                        'Unit 6: Combustion and Flame — types of combustion and fire safety',
                        'Unit 7: Conservation of Plants and Animals — biodiversity and reserves',
                        'Unit 8: Cell — Structure and Functions — plant and animal cells',
                        'Unit 9: Reproduction in Animals — fertilisation and embryo development',
                        'Unit 10: Reaching the Age of Adolescence — hormonal changes and hygiene',
                        'Unit 11: Force and Pressure — contact and non-contact forces',
                        'Unit 12: Friction — advantages, disadvantages, and reducing friction',
                        'Unit 13: Sound — propagation, amplitude, and frequency',
                        'Unit 14: Chemical Effects of Electric Current — electroplating',
                        'Unit 15: Some Natural Phenomena — lightning and earthquakes',
                        'Unit 16: Light — laws of reflection and human eye',
                        'Unit 17: Stars and the Solar System — constellations and phases of moon',
                        'Unit 18: Pollution of Air and Water — causes and control measures',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading — literary and factual long passages',
                        'Unit 2: Grammar — active/passive, reported speech, and modals',
                        'Unit 3: Writing — formal essays (250 words), reports, and articles',
                        'Unit 4: Literature — Honeydew and It So Happened supplementary',
                        'Unit 5: Notice and Poster Writing — format and content',
                        'Unit 6: Integrated Grammar — transformation of sentences',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: रचना के आधार पर वाक्य भेद — sentence types',
                        'Unit 2: अलंकार — अनुप्रास, उपमा, रूपक',
                        'Unit 3: अपठित गद्यांश और कविता — exam-style practice',
                        'Unit 4: निबंध, रिपोर्ट, और संवाद लेखन — formal writing',
                        'Unit 5: Bharat Ki Khoj / Vasant chapters — prose and poetry analysis',
                    ],
                ],
                [
                    'name' => 'SST',
                    'units' => [
                        'Unit 1: History — How, When and Where — colonial records and surveys',
                        'Unit 2: History — From Trade to Territory — East India Company',
                        'Unit 3: History — Ruling the Countryside — revenue systems',
                        'Unit 4: History — Tribals, Dikus and the Vision of a Golden Age',
                        'Unit 5: History — When People Rebel — 1857 revolt',
                        'Unit 6: History — Civilising the "Native", Educating the Nation',
                        'Unit 7: History — Women, Caste and Reform — social movements',
                        'Unit 8: History — The Making of the National Movement (1870s–1947)',
                        'Unit 9: Geography — Resources — types and conservation',
                        'Unit 10: Geography — Land, Soil, Water, Natural Vegetation and Wildlife',
                        'Unit 11: Geography — Agriculture and industries in India',
                        'Unit 12: Geography — Human Resources — population and distribution',
                        'Unit 13: Civics — The Indian Constitution — features and Preamble',
                        'Unit 14: Civics — Understanding Secularism and Parliament',
                        'Unit 15: Civics — Understanding Laws and Judiciary',
                    ],
                ],
            ],
        ],
        9 => [
            'class' => 9,
            'session' => $session,
            'title' => 'Class 9 CBSE Syllabus 2026-27',
            'description' => 'Secondary school syllabus for Class 9 covering polynomials, atoms and molecules, democratic politics, and foundational board exam skills.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Number Systems — irrational numbers and real number line',
                        'Unit 2: Polynomials — zeros, factor theorem, and algebraic identities',
                        'Unit 3: Coordinate Geometry — Cartesian plane and plotting points',
                        'Unit 4: Linear Equations in Two Variables — graphing and applications',
                        'Unit 5: Introduction to Euclid\'s Geometry — axioms and postulates',
                        'Unit 6: Lines and Angles — parallel lines and angle properties',
                        'Unit 7: Triangles — congruence rules and inequalities',
                        'Unit 8: Quadrilaterals — properties and mid-point theorem',
                        'Unit 9: Circles — chords, arcs, and angle subtended',
                        'Unit 10: Heron\'s Formula — area of triangles',
                        'Unit 11: Surface Areas and Volumes — cubes, cuboids, cylinders, cones, spheres',
                        'Unit 12: Statistics — mean, median, mode of grouped data',
                        'Unit 13: Probability — experimental approach and events',
                    ],
                ],
                [
                    'name' => 'Science',
                    'units' => [
                        'Unit 1: Matter in Our Surroundings — states of matter and evaporation',
                        'Unit 2: Is Matter Around Us Pure? — mixtures, solutions, and colloids',
                        'Unit 3: Atoms and Molecules — laws of chemical combination and mole concept',
                        'Unit 4: Structure of the Atom — electrons, protons, neutrons, and isotopes',
                        'Unit 5: The Fundamental Unit of Life — cell organelles and osmosis',
                        'Unit 6: Tissues — plant and animal tissues',
                        'Unit 7: Motion — distance, displacement, velocity, and equations of motion',
                        'Unit 8: Force and Laws of Motion — Newton\'s three laws',
                        'Unit 9: Gravitation — universal law and free fall',
                        'Unit 10: Work and Energy — kinetic and potential energy',
                        'Unit 11: Sound — propagation, echo, and SONAR',
                        'Unit 12: Improvement in Food Resources — crop varieties and animal husbandry',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading Comprehension — discursive and case-based passages (CBSE pattern)',
                        'Unit 2: Writing — descriptive paragraphs, diary entries, and story writing',
                        'Unit 3: Grammar — tenses, modals, determiners, and subject–verb concord',
                        'Unit 4: Literature — Beehive prose and Moments supplementary reader',
                        'Unit 5: Formal Letter Writing — complaint, enquiry, and placement letters',
                        'Unit 6: Integrated Grammar — editing, omission, and sentence reordering',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: अपठित गद्यांश — 08-mark unseen passage practice',
                        'Unit 2: व्याकरण — समास, मुहावरे, and वाक्य शुद्धि',
                        'Unit 3: कविता खंड — Kshitij and Kritika chapters',
                        'Unit 4: लेखन — formal letters, essays, and advertisements',
                        'Unit 5: Gadya Path — prose comprehension and summary',
                    ],
                ],
                [
                    'name' => 'Social Science',
                    'units' => [
                        'Unit 1: History — The French Revolution and socialism in Europe',
                        'Unit 2: History — Socialism in Europe and the Russian Revolution',
                        'Unit 3: History — Nazism and the Rise of Hitler',
                        'Unit 4: History — Forest Society and Colonialism',
                        'Unit 5: History — Pastoralists in the Modern World',
                        'Unit 6: Geography — India — Size and Location; Physical Features',
                        'Unit 7: Geography — Drainage, Climate, and Natural Vegetation',
                        'Unit 8: Geography — Population — size, distribution, and growth',
                        'Unit 9: Political Science — What Is Democracy? Why Democracy?',
                        'Unit 10: Political Science — Constitutional Design and Electoral Politics',
                        'Unit 11: Political Science — Working of Institutions and Democratic Rights',
                        'Unit 12: Economics — The Story of Village Palampur and People as Resource',
                        'Unit 13: Economics — Poverty as a Challenge and Food Security',
                    ],
                ],
            ],
        ],
        10 => [
            'class' => 10,
            'session' => $session,
            'title' => 'Class 10 CBSE Syllabus 2026-27',
            'description' => 'Board exam year syllabus for Class 10 with complete NCERT coverage in Mathematics, Science, English, Hindi, and Social Science.',
            'subjects' => [
                [
                    'name' => 'Mathematics',
                    'units' => [
                        'Unit 1: Real Numbers — Euclid\'s division lemma and fundamental theorem of arithmetic',
                        'Unit 2: Polynomials — zeros and relationship between zeros and coefficients',
                        'Unit 3: Pair of Linear Equations in Two Variables — graphical and algebraic methods',
                        'Unit 4: Quadratic Equations — nature of roots and word problems',
                        'Unit 5: Arithmetic Progressions — nth term and sum of n terms',
                        'Unit 6: Triangles — similarity criteria and Pythagoras theorem',
                        'Unit 7: Coordinate Geometry — distance and section formulas',
                        'Unit 8: Introduction to Trigonometry — ratios and complementary angles',
                        'Unit 9: Some Applications of Trigonometry — heights and distances',
                        'Unit 10: Circles — tangent properties and number of tangents',
                        'Unit 11: Areas Related to Circles — sectors and segments',
                        'Unit 12: Surface Areas and Volumes — combinations of solids',
                        'Unit 13: Statistics — mean, median, mode of grouped data and ogives',
                        'Unit 14: Probability — classical definition and simple events',
                    ],
                ],
                [
                    'name' => 'Science',
                    'units' => [
                        'Unit 1: Chemical Reactions and Equations — types and balancing',
                        'Unit 2: Acids, Bases and Salts — pH scale and important salts',
                        'Unit 3: Metals and Non-metals — reactivity series and extraction',
                        'Unit 4: Carbon and Its Compounds — nomenclature and functional groups',
                        'Unit 5: Life Processes — nutrition, respiration, transport, and excretion',
                        'Unit 6: Control and Coordination — nervous and hormonal systems',
                        'Unit 7: How Do Organisms Reproduce? — asexual and sexual reproduction',
                        'Unit 8: Heredity and Evolution — Mendel\'s laws and speciation',
                        'Unit 9: Light — Reflection and Refraction — mirrors and lenses',
                        'Unit 10: Human Eye and Colourful World — defects and dispersion',
                        'Unit 11: Electricity — Ohm\'s law, resistivity, and power',
                        'Unit 12: Magnetic Effects of Electric Current — electromagnets and motors',
                        'Unit 13: Sources of Energy — conventional and non-conventional',
                        'Unit 14: Our Environment — food chains, ozone, and waste management',
                    ],
                ],
                [
                    'name' => 'English',
                    'units' => [
                        'Unit 1: Reading — unseen passages (factual and literary) per board pattern',
                        'Unit 2: Writing — analytical paragraphs, articles, and reports',
                        'Unit 3: Grammar — all prescribed topics including gap filling and editing',
                        'Unit 4: Literature — First Flight and Footprints Without Feet',
                        'Unit 5: Formal Letter and Analytical Paragraph — board exam formats',
                        'Unit 6: Literature Long Answer — theme, character, and message questions',
                    ],
                ],
                [
                    'name' => 'Hindi',
                    'units' => [
                        'Unit 1: अपठित गद्यांश — board-style practice papers',
                        'Unit 2: व्याकरण — पद-परिचय, वाक्य शुद्धि, and अलंकार',
                        'Unit 3: कविता — Sparsh and Sanchayan chapters',
                        'Unit 4: लेखन — formal letters, essays, and advertisements (board format)',
                        'Unit 5: गद्य — long-answer literature questions',
                    ],
                ],
                [
                    'name' => 'Social Science',
                    'units' => [
                        'Unit 1: History — The Rise of Nationalism in Europe and India',
                        'Unit 2: History — Nationalism in India — Non-Cooperation to Civil Disobedience',
                        'Unit 3: History — The Making of a Global World and Print Culture',
                        'Unit 4: Geography — Resources and Development; Forest and Wildlife',
                        'Unit 5: Geography — Water Resources and Agriculture',
                        'Unit 6: Geography — Minerals, Energy, and Manufacturing Industries',
                        'Unit 7: Geography — Lifelines of National Economy — transport and communication',
                        'Unit 8: Political Science — Power Sharing and Federalism',
                        'Unit 9: Political Science — Gender, Religion and Caste; Political Parties',
                        'Unit 10: Political Science — Outcomes of Democracy and Challenges',
                        'Unit 11: Economics — Development and Sectors of the Indian Economy',
                        'Unit 12: Economics — Money and Credit; Globalisation and Consumer Rights',
                    ],
                ],
            ],
        ],
        11 => [
            'class' => 11,
            'session' => $session,
            'title' => 'Class 11 CBSE Syllabus 2026-27',
            'description' => 'Senior secondary syllabus overview for Class 11 across Science, Commerce, and Arts streams. Students choose one stream; subjects below reflect typical CBSE combinations.',
            'subjects' => [
                [
                    'name' => 'English Core',
                    'units' => [
                        'Unit 1: Reading Comprehension — unseen passages and note-making',
                        'Unit 2: Advanced Writing — articles, speeches, and reports (120–150 words)',
                        'Unit 3: Grammar — integrated exercises per CBSE Class 11 pattern',
                        'Unit 4: Literature — Hornbill and Snapshots supplementary reader',
                        'Unit 5: Long Reading Text — prescribed novel/chapter analysis',
                    ],
                ],
                [
                    'name' => 'Physics (Science Stream)',
                    'units' => [
                        'Unit 1: Physical World and Measurement — units, dimensions, and errors',
                        'Unit 2: Kinematics — motion in a straight line and plane',
                        'Unit 3: Laws of Motion — Newton\'s laws and friction',
                        'Unit 4: Work, Energy and Power — conservation laws',
                        'Unit 5: Motion of System of Particles and Rigid Body — centre of mass and rotation',
                        'Unit 6: Gravitation — Kepler\'s laws and satellites',
                        'Unit 7: Properties of Bulk Matter — elasticity, fluid mechanics, and thermal properties',
                        'Unit 8: Thermodynamics — laws and heat engines',
                        'Unit 9: Behaviour of Perfect Gases and Kinetic Theory',
                        'Unit 10: Oscillations and Waves — SHM and sound waves',
                    ],
                ],
                [
                    'name' => 'Chemistry (Science Stream)',
                    'units' => [
                        'Unit 1: Some Basic Concepts of Chemistry — mole concept and stoichiometry',
                        'Unit 2: Structure of Atom — quantum numbers and electronic configuration',
                        'Unit 3: Classification of Elements and Periodicity',
                        'Unit 4: Chemical Bonding and Molecular Structure — VSEPR and hybridisation',
                        'Unit 5: States of Matter — gas laws and intermolecular forces',
                        'Unit 6: Thermodynamics — enthalpy and Hess\'s law',
                        'Unit 7: Equilibrium — chemical and ionic equilibrium',
                        'Unit 8: Redox Reactions — oxidation number and balancing',
                        'Unit 9: Organic Chemistry — nomenclature, isomerism, and reaction mechanisms intro',
                        'Unit 10: Hydrocarbons — alkanes, alkenes, and alkynes',
                    ],
                ],
                [
                    'name' => 'Mathematics (Science Stream)',
                    'units' => [
                        'Unit 1: Sets — operations and Venn diagrams',
                        'Unit 2: Relations and Functions — domain, range, and types',
                        'Unit 3: Trigonometric Functions — identities and equations',
                        'Unit 4: Complex Numbers and Quadratic Equations',
                        'Unit 5: Linear Inequalities — graphical solutions',
                        'Unit 6: Permutations and Combinations',
                        'Unit 7: Binomial Theorem — general and middle terms',
                        'Unit 8: Sequences and Series — AP, GP, and special series',
                        'Unit 9: Straight Lines — slope, equations, and distance',
                        'Unit 10: Conic Sections — circle, parabola, ellipse, hyperbola',
                        'Unit 11: Introduction to Three Dimensional Geometry',
                        'Unit 12: Limits and Derivatives — first principles and rules',
                        'Unit 13: Statistics — measures of dispersion',
                        'Unit 14: Probability — axiomatic approach',
                    ],
                ],
                [
                    'name' => 'Biology (Science Stream — Medical)',
                    'units' => [
                        'Unit 1: The Living World — biodiversity and classification',
                        'Unit 2: Biological Classification — five kingdom system',
                        'Unit 3: Plant Kingdom — algae to angiosperms',
                        'Unit 4: Animal Kingdom — invertebrates and vertebrates',
                        'Unit 5: Morphology of Flowering Plants',
                        'Unit 6: Anatomy of Flowering Plants — tissues and secondary growth',
                        'Unit 7: Structural Organisation in Animals',
                        'Unit 8: Cell: The Unit of Life — organelles and cell cycle',
                        'Unit 9: Biomolecules — carbohydrates, proteins, and enzymes',
                        'Unit 10: Cell Cycle and Cell Division — mitosis and meiosis',
                        'Unit 11: Transport in Plants and Mineral Nutrition',
                        'Unit 12: Photosynthesis in Higher Plants',
                        'Unit 13: Respiration in Plants and Plant Growth and Development',
                        'Unit 14: Digestion and Absorption; Breathing and Exchange of Gases',
                        'Unit 15: Body Fluids and Circulation; Excretory Products',
                        'Unit 16: Locomotion and Movement; Neural Control and Coordination',
                        'Unit 17: Chemical Coordination and Integration',
                    ],
                ],
                [
                    'name' => 'Accountancy (Commerce Stream)',
                    'units' => [
                        'Unit 1: Introduction to Accounting — concepts, conventions, and GAAP',
                        'Unit 2: Theory Base of Accounting — IFRS intro and accounting standards',
                        'Unit 3: Recording of Transactions — journal, ledger, and trial balance',
                        'Unit 4: Bank Reconciliation Statement',
                        'Unit 5: Depreciation, Provisions and Reserves',
                        'Unit 6: Bills of Exchange — promissory notes and honour/dishonour',
                        'Unit 7: Trial Balance and Rectification of Errors',
                        'Unit 8: Financial Statements — trading, P&L, and balance sheet',
                        'Unit 9: Accounts from Incomplete Records',
                        'Unit 10: Computers in Accounting — Tally and spreadsheet basics',
                    ],
                ],
                [
                    'name' => 'Business Studies (Commerce Stream)',
                    'units' => [
                        'Unit 1: Nature and Purpose of Business — economic and social objectives',
                        'Unit 2: Forms of Business Organisation — sole proprietorship to company',
                        'Unit 3: Public, Private and Global Enterprises',
                        'Unit 4: Business Services — banking, insurance, and communication',
                        'Unit 5: Emerging Modes of Business — e-business and outsourcing',
                        'Unit 6: Social Responsibility of Business and Business Ethics',
                        'Unit 7: Sources of Business Finance — equity, debentures, and retained earnings',
                        'Unit 8: Small Business and Entrepreneurship',
                        'Unit 9: Internal Trade — wholesale, retail, and international trade intro',
                        'Unit 10: International Business — export-import procedures',
                    ],
                ],
                [
                    'name' => 'Economics (Commerce & Arts Stream)',
                    'units' => [
                        'Unit 1: Introduction — central problems of an economy',
                        'Unit 2: Collection, Organisation and Presentation of Data',
                        'Unit 3: Statistical Tools — mean, median, mode, correlation, and index numbers',
                        'Unit 4: Introduction to Microeconomics — demand and supply',
                        'Unit 5: Consumer\'s Equilibrium and Demand — utility analysis and elasticity',
                        'Unit 6: Producer Behaviour and Supply — cost curves and revenue',
                        'Unit 7: Forms of Market and Price Determination — perfect and imperfect competition',
                        'Unit 8: Indian Economic Development — liberalisation and globalisation',
                    ],
                ],
                [
                    'name' => 'History (Arts Stream)',
                    'units' => [
                        'Unit 1: From the Beginning of Time — early societies and writing',
                        'Unit 2: Writing and City Life — Mesopotamia and urbanisation',
                        'Unit 3: An Empire Across Three Continents — Roman Empire',
                        'Unit 4: The Central Islamic Lands — rise of Islam and caliphates',
                        'Unit 5: Nomadic Empires — Mongols and their impact',
                        'Unit 6: The Three Orders — feudal Europe',
                        'Unit 7: Changing Cultural Traditions — Renaissance and Reformation',
                        'Unit 8: Confrontation of Cultures — voyages and colonial encounters',
                        'Unit 9: The Industrial Revolution — technology and social change',
                        'Unit 10: Displacing Indigenous Peoples — Americas and Australia',
                        'Unit 11: Paths to Modernisation — China and Japan',
                    ],
                ],
                [
                    'name' => 'Political Science (Arts Stream)',
                    'units' => [
                        'Unit 1: Political Theory — freedom, equality, and justice',
                        'Unit 2: Rights — natural, legal, and human rights',
                        'Unit 3: Citizenship — duties, nationality, and global citizenship',
                        'Unit 4: Nationalism — nation, state, and self-determination',
                        'Unit 5: Secularism — Indian and Western models',
                        'Unit 6: Constitution: Why and How? — making of the Indian Constitution',
                        'Unit 7: Election and Representation — electoral systems and reforms',
                        'Unit 8: Legislature, Executive, and Judiciary — structure and functions',
                        'Unit 9: Federalism and Local Governments — Panchayati Raj',
                        'Unit 10: Constitution as a Living Document — amendments and debates',
                    ],
                ],
            ],
        ],
        12 => [
            'class' => 12,
            'session' => $session,
            'title' => 'Class 12 CBSE Syllabus 2026-27',
            'description' => 'Final board exam syllabus for Class 12 with stream-specific subjects in Science, Commerce, and Arts, plus English Core common to all streams.',
            'subjects' => [
                [
                    'name' => 'English Core',
                    'units' => [
                        'Unit 1: Reading Comprehension — unseen passages with vocabulary and inference',
                        'Unit 2: Advanced Writing — reports, articles, and job applications',
                        'Unit 3: Literature — Flamingo and Vistas supplementary reader',
                        'Unit 4: Long Reading Text — novel-based long answer questions',
                        'Unit 5: Board Exam Practice — integrated grammar and writing tasks',
                    ],
                ],
                [
                    'name' => 'Physics (Science Stream)',
                    'units' => [
                        'Unit 1: Electrostatics — Coulomb\'s law, field, and potential',
                        'Unit 2: Current Electricity — Ohm\'s law, Kirchhoff\'s rules, and Wheatstone bridge',
                        'Unit 3: Magnetic Effects of Current and Magnetism — Biot-Savart and Ampere\'s law',
                        'Unit 4: Electromagnetic Induction and Alternating Currents',
                        'Unit 5: Electromagnetic Waves — Maxwell\'s equations intro and spectrum',
                        'Unit 6: Optics — ray optics, wave optics, and optical instruments',
                        'Unit 7: Dual Nature of Radiation and Matter — photoelectric effect',
                        'Unit 8: Atoms and Nuclei — Bohr model and radioactivity',
                        'Unit 9: Electronic Devices — semiconductors, diodes, and logic gates',
                    ],
                ],
                [
                    'name' => 'Chemistry (Science Stream)',
                    'units' => [
                        'Unit 1: Solid State — crystal lattices and defects',
                        'Unit 2: Solutions — concentration terms and colligative properties',
                        'Unit 3: Electrochemistry — cells, Nernst equation, and conductance',
                        'Unit 4: Chemical Kinetics — rate law and activation energy',
                        'Unit 5: Surface Chemistry — adsorption, catalysis, and colloids',
                        'Unit 6: General Principles of Isolation of Elements — metallurgy',
                        'Unit 7: p-Block Elements — groups 15, 16, 17, and 18',
                        'Unit 8: d- and f-Block Elements — transition and inner transition metals',
                        'Unit 9: Coordination Compounds — nomenclature and isomerism',
                        'Unit 10: Haloalkanes and Haloarenes — SN1/SN2 mechanisms',
                        'Unit 11: Alcohols, Phenols and Ethers — preparation and properties',
                        'Unit 12: Aldehydes, Ketones and Carboxylic Acids',
                        'Unit 13: Amines and Biomolecules — carbohydrates, proteins, and nucleic acids',
                        'Unit 14: Polymers and Chemistry in Everyday Life',
                    ],
                ],
                [
                    'name' => 'Mathematics (Science Stream)',
                    'units' => [
                        'Unit 1: Relations and Functions — types and inverse trigonometric functions',
                        'Unit 2: Algebra — matrices and determinants',
                        'Unit 3: Calculus — continuity, differentiability, and applications of derivatives',
                        'Unit 4: Integrals — indefinite and definite integration',
                        'Unit 5: Applications of Integrals — area under curves',
                        'Unit 6: Differential Equations — formation and solution methods',
                        'Unit 7: Vector Algebra — dot and cross products',
                        'Unit 8: Three Dimensional Geometry — lines and planes',
                        'Unit 9: Linear Programming — graphical method',
                        'Unit 10: Probability — conditional probability and Bayes\' theorem',
                    ],
                ],
                [
                    'name' => 'Biology (Science Stream — Medical)',
                    'units' => [
                        'Unit 1: Reproduction — organisms, flowering plants, and human reproduction',
                        'Unit 2: Genetics and Evolution — Mendelian genetics, molecular basis, and evolution',
                        'Unit 3: Biology and Human Welfare — health, microbes, and immunity',
                        'Unit 4: Biotechnology — principles and applications (PCR, GMOs)',
                        'Unit 5: Ecology and Environment — populations, ecosystems, and biodiversity',
                        'Unit 6: Organisms and Populations — adaptation and interactions',
                        'Unit 7: Environmental Issues — pollution, global warming, and conservation',
                    ],
                ],
                [
                    'name' => 'Accountancy (Commerce Stream)',
                    'units' => [
                        'Unit 1: Accounting for Partnership Firms — fundamentals and profit sharing',
                        'Unit 2: Reconstitution of Partnership — admission, retirement, and death',
                        'Unit 3: Dissolution of Partnership Firm',
                        'Unit 4: Accounting for Share Capital — issue and forfeiture of shares',
                        'Unit 5: Accounting for Debentures — issue and redemption',
                        'Unit 6: Analysis of Financial Statements — ratio analysis and cash flow statement',
                        'Unit 7: Computerised Accounting — database and accounting software',
                    ],
                ],
                [
                    'name' => 'Business Studies (Commerce Stream)',
                    'units' => [
                        'Unit 1: Nature and Significance of Management — principles and functions',
                        'Unit 2: Principles of Management — Fayol and Taylor',
                        'Unit 3: Business Environment — economic and social environment',
                        'Unit 4: Planning and Organising — types and process',
                        'Unit 5: Staffing and Directing — recruitment, motivation, and leadership',
                        'Unit 6: Controlling — steps and techniques',
                        'Unit 7: Financial Management — capital structure and dividend decisions',
                        'Unit 8: Financial Markets — money and capital markets',
                        'Unit 9: Marketing Management — mix and consumer protection',
                        'Unit 10: Consumer Protection — rights and redressal mechanisms',
                    ],
                ],
                [
                    'name' => 'Economics (Commerce & Arts Stream)',
                    'units' => [
                        'Unit 1: Introduction to Macroeconomics — national income accounting',
                        'Unit 2: Money and Banking — RBI, credit creation, and monetary policy',
                        'Unit 3: Income Determination — aggregate demand and supply',
                        'Unit 4: Government Budget and the Economy — fiscal deficit and public goods',
                        'Unit 5: Balance of Payments — current and capital account',
                        'Unit 6: Indian Economic Development — poverty, human capital, and employment',
                        'Unit 7: Rural Development and Infrastructure',
                        'Unit 8: Environment and Sustainable Development',
                        'Unit 9: Comparative Development Experiences — India, China, and Pakistan',
                    ],
                ],
                [
                    'name' => 'History (Arts Stream)',
                    'units' => [
                        'Unit 1: Bricks, Beads and Bones — Harappan civilisation',
                        'Unit 2: Kings, Farmers and Towns — Mauryan and post-Mauryan India',
                        'Unit 3: Kinship, Caste and Class — early societies',
                        'Unit 4: Thinkers, Beliefs and Buildings — Buddhism and Jainism',
                        'Unit 5: Through the Eyes of Travellers — Al-Biruni and Ibn Battuta',
                        'Unit 6: Bhakti-Sufi Traditions — religious movements',
                        'Unit 7: An Imperial Capital: Vijayanagara',
                        'Unit 8: Peasants, Zamindars and the State — Mughal agrarian society',
                        'Unit 9: Colonialism and the Countryside — revenue systems',
                        'Unit 10: Mahatma Gandhi and the National Movement',
                        'Unit 11: Understanding Partition — politics, memories, and experiences',
                        'Unit 12: Framing the Constitution — debates and vision',
                    ],
                ],
                [
                    'name' => 'Political Science (Arts Stream)',
                    'units' => [
                        'Unit 1: The Cold War Era — bipolarity and NAM',
                        'Unit 2: The End of Bipolarity — disintegration of USSR and rise of US',
                        'Unit 3: US Hegemony in World Politics — soft, hard, and structural power',
                        'Unit 4: Alternative Centres of Power — EU, China, and Japan',
                        'Unit 5: Contemporary South Asia — India and neighbours',
                        'Unit 6: International Organisations — UN and its reform',
                        'Unit 7: Security in the Contemporary World — terrorism and human security',
                        'Unit 8: Environment and Natural Resources — global environmental politics',
                        'Unit 9: Globalisation — economic, cultural, and political dimensions',
                        'Unit 10: Challenges of Nation Building — integration of princely states',
                        'Unit 11: Planned Development and India\'s Foreign Policy',
                        'Unit 12: Regional Aspirations and Recent Developments in Indian Politics',
                    ],
                ],
            ],
        ],
    ];

    return $data;
}

function get_syllabus(int $classNum): ?array
{
    $data = syllabus_data();
    return $data[$classNum] ?? null;
}

function get_all_syllabi(): array
{
    return array_values(syllabus_data());
}
